### model
model_name_or_path: ../models/DeepSeek-Prover-V2-7B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset: FormalML
template: alpaca
cutoff_len: 2048
max_samples: null
overwrite_cache: true
preprocessing_num_workers: 32
dataloader_num_workers: 16

### output
output_dir: saves/deepseekprover-v2/expertIteration/round2/full/sft
logging_steps: 100
save_safetensors: true  
save_total_limit: 1 
save_steps: 2000
save_strategy: steps
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 2e-4
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### deepspeed
deepspeed: my_expertIterationConfigs/round2/train.yaml
